### ISSUE TITLE
원화 조회

### ISSUE THREAD

**Issue by puzzlecollector** [sharebook-kr/pybithumb#28]
잔고에 원화가 얼마나 있는지는 어떻게 조회해야하나요?

**Comment by mr-yoo** [comment]
`get_balance` 메서드는 하나의 튜플을 반환합니다. 튜플 안에는 네 개의 값이 저장되어 있는데 앞에서부터 순서대로 암호화폐의 총 잔고, 거래 중인 암호화폐의 수량, 보유 중인 총원화, 주문에 사용된 원화를 의미합니다. 따라서 2번 위치를 인덱싱하면 원하는 정보를 얻을 수 있습니다.

```python
balance = bithumb.get_balance("BTC")
print(balance[2])
```
