### ISSUE TITLE
history.get_ohlcv() may be unavailable

### ISSUE THREAD

**Issue by Seonwhee-Genome** [sharebook-kr/pybithumb#5]
The latest ohlcv information was 2019-08-18 22:50:00 KST.
I think candle resources in Bithumb had been changed.
Please check this issue.

어제 저녁 10시 50분이 마지막 캔들 정보 였는데, 아무래도 차트 데이터 json이 위치한 경로가 바뀌었거나 막힌 것 같습니다. 확인부탁드립니다.

**Comment by mr-yoo** [comment]
You're right. Bithumb server's URL requesting the OHLCV data had been changed as follows.
- "https://m.bithumb.com/trade/chart/"
The problem you mentioned was resolved by "5fc12c1" commit.

지적 내용이 맞습니다. OHLCV 데이터를 요청하는 페이지가 변경되었습니다. 위 내용은 "5fc12c1" 커밋에서 수정했습니다. 

감사합니다.
